name: smart_home
description: Smart Home App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  intl: ^0.18.1
  provider: ^6.0.5
  go_router: ^10.1.2
  google_fonts: ^5.1.0
  flutter_blue_plus: ^1.14.11
  dotenv: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/

flutter_gen:
  line_length: 80

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#000000"
    theme_color: "#151928"
  windows:
    generate: true
    image_path: "assets/images/logo.png"
    icon_size: 256
  macos:
    generate: true
    image_path: "assets/images/logo.png"
    remove_alpha_ios: true